
import { create } from 'zustand';

interface LanguageState {
  language: 'en' | 'sw';
  setLanguage: (lang: 'en' | 'sw') => void;
  t: typeof translations.en;
}

const translations = {
  en: {
    appName: "Pesa Smart Plan Kenya",
    appDescription: "Pay in installments, save smart, grow your business",
    customer: "Customer",
    business: "Business",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    name: "Name",
    phone: "Phone Number",
    businessName: "Business Name",
    logout: "Logout",
    dashboard: "Dashboard",
    products: "Products",
    customers: "Customers",
    analytics: "Analytics",
    savings: "Savings",
    installments: "Installments",
    emergency: "Emergency Fund",
    profile: "Profile",
    addProduct: "Add Product",
    productName: "Product Name",
    price: "Price (KSH)",
    category: "Category",
    maxInstallmentPeriod: "Max Installment Period (months)",
    electronics: "Electronics",
    furniture: "Furniture",
    clothing: "Clothing",
    land: "Land/Property",
    other: "Other",
    save: "Save",
    cancel: "Cancel",
    totalSavings: "Total Savings",
    availableEmergency: "Available for Emergency",
    currentInstallments: "Current Installments",
    savingsPeriod: "Savings Period",
    months: "months",
    payNow: "Pay Now",
    buyOnInstallment: "Buy on Installment",
    selectPeriod: "Select Payment Period",
    monthlyPayment: "Monthly Payment",
    emergencyWithdraw: "Emergency Withdraw",
    amount: "Amount",
    reason: "Reason",
    withdraw: "Withdraw",
    progress: "Progress",
    congratulations: "Congratulations on your savings progress!",
    keepGoing: "Keep going! You're doing great!",
    almostThere: "Almost there! Stay focused on your goals!",
  },
  sw: {
    appName: "Pesa Smart Plan Kenya",
    appDescription: "Lipa kwa awamu, okoa kwa busara, kua biashara yako",
    customer: "Mteja",
    business: "Biashara",
    login: "Ingia",
    register: "Jisajili",
    email: "Barua pepe",
    password: "Nywila",
    name: "Jina",
    phone: "Namba ya Simu",
    businessName: "Jina la Biashara",
    logout: "Toka",
    dashboard: "Dashibodi",
    products: "Bidhaa",
    customers: "Wateja",
    analytics: "Uchambuzi",
    savings: "Akiba",
    installments: "Malipo ya Awamu",
    emergency: "Fedha za Dharura",
    profile: "Wasifu",
    addProduct: "Ongeza Bidhaa",
    productName: "Jina la Bidhaa",
    price: "Bei (KSH)",
    category: "Jamii",
    maxInstallmentPeriod: "Muda wa Juu wa Malipo ya Awamu (miezi)",
    electronics: "Vifaa vya Umeme",
    furniture: "Fanicha",
    clothing: "Nguo",
    land: "Ardhi/Mali",
    other: "Nyingine",
    save: "Hifadhi",
    cancel: "Futa",
    totalSavings: "Jumla ya Akiba",
    availableEmergency: "Inapatikana kwa Dharura",
    currentInstallments: "Malipo ya Awamu ya Sasa",
    savingsPeriod: "Muda wa Kuhifadhi",
    months: "miezi",
    payNow: "Lipa Sasa",
    buyOnInstallment: "Nunua kwa Awamu",
    selectPeriod: "Chagua Muda wa Malipo",
    monthlyPayment: "Malipo ya Kila Mwezi",
    emergencyWithdraw: "Toa Fedha za Dharura",
    amount: "Kiasi",
    reason: "Sababu",
    withdraw: "Toa",
    progress: "Maendeleo",
    congratulations: "Hongera kwa maendeleo yako ya akiba!",
    keepGoing: "Endelea! Unafanya vizuri!",
    almostThere: "Karibu kumaliza! Zingatia malengo yako!",
  }
};

export const useLanguage = create<LanguageState>((set, get) => ({
  language: 'en',
  setLanguage: (lang) => set({ 
    language: lang,
    t: translations[lang]
  }),
  t: translations.en,
}));
