// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lijtadxkzuneijvvcznm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpanRhZHhrenVuZWlqdnZjem5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODQwNzYsImV4cCI6MjA2NTU2MDA3Nn0.shNkY9zVvQ0XS0x1BCd-i6mycuRH3GdChGbqHWcI7FA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);